---
title: Talks and Presentations
---

### Contributed Talks

- *Chebyshev Polynomials on a Jordan Arc*, OPSFA 18, Doshisha University (Kyoto, Japan), August 2026. 

- *An upper bound for the Widom factors on Jordan arcs*, Spectral Theory by the Lakes, Lancaster University (Lancaster, UK), April 2026. 

- *Extremal polynomials on a Jordan curve or arc*, Bench Math Session 2026, Jagiellonian University (Kraków, Poland), February 2026. 

- *Extremal polynomials on a Jordan curve or arc*, OTA 2024, TU Wien (Vienna, Austria), July 2024. 

### Seminar talks

- *Scaling limits of Chebyshev polynomials at a hard edge*, LTH (Lund, Sweden), September 2026.

- *Chebyshev Polynome und Widom-Faktoren*, TU Wien (Vienna, Austria), April 2025

- *Asymptotics of extremal polynomials on a Jordan curve or arc*, KU Leuven (Leuven, Belgium), October 2025.

### Posters

- *Chebyshev Polynomials on a Jordan Arc*, FoCM 2026, Universität Wien (Vienna, Austria), July 2026. 

- *Szegő's theorem on a Jordan arc*, OPSFOTA 2024, University of Bristol (Bristol, UK), poster and short-fire session, July 2024. 

- *Szegő's theorem on a Jordan arc*, ARNO 2024, KU Leuven (Leuven, Belgium), May 2024. 

### Attended Conferences and Workshops

- *Random Matrix Theory and Integrable Systems*, Great Bay University (Dongguan, China), January 2026. 

- *SQuaRE Meeting on Weighted Chebyshev/Extremal Polynomials*, American Institute of Mathematics (Pasadena, USA), May 2025. 

- *Operator Theory and Indefinite Inner Products*, TU Wien (Vienna, Austria), February 2025. 

